# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios_native_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  flutter_application_path = '../flutter_app'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)
  # Pods for ios_native_app

end
